### ISSUE TITLE
Potential Duplicates in Metrics Daily Transactions

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#102]
Discord user `aria` posted:

> Hey - I am using the near.core.metrics_daily_transaction table and I am seeing a large number of duplicate entries for each day (https://app.flipsidecrypto.com/velocity/queries/0984f1ea-6ba5-4c23-ad97-ac6f1b84a2f7). Is this intended?

**Comment by D0R11** [comment]
Anyone else tried to replicate this issue? I checked the query but I don't see any duplicates yet.

**Comment by D0R11** [comment]
okay I was able to replicate. Will take on this issue

**Comment by D0R11** [comment]
Duplicates start on the 30th of July. It's weird how I did the same query on snowflake for the daily transactions but the duplicates didn't appear. Will be checking out the macros if it's working as intended.

**Comment by forgxyz** [comment]
Metrics deprecated - closing
