### ISSUE TITLE
Missing Block Hashes

### ISSUE THREAD

**Issue by sedaghatfar** [MetricsDAO/near_dbt#106]
Based on prev_hash

```with silver_blocks as (
SELECT 
    block_id
    , block_timestamp
    , block_hash
    , tx_count
    , prev_hash
    , lag(block_hash) over (order by block_timestamp asc,block_id asc) as prior_hash
    , lag(block_id)   over (order by block_timestamp asc,block_id asc) as prior_block_id
    , block_id - prior_block_id as block_delta
FROM NEAR_DEV.SILVER.BLOCKS b 
    )
SELECT *
FROM silver_blocks
WHERE prior_hash <> prev_hash;
```

Missing in the chainwalkers as well

```
SELECT *
FROM CHAINWALKERS.PROD.NEAR_BLOCKS
WHERE block_id = '71686271';
```

What is the process to re process missing blocks?

**Comment by forgxyz** [comment]
This is great, thanks. Addresses issue #84 

Result of this test:
| BLOCK_ID | BLOCK_TIMESTAMP          | BLOCK_HASH                                   | TX_COUNT | PREV_HASH                                    | PRIOR_HASH                                   | PRIOR_BLOCK_ID | BLOCK_DELTA |
|----------|--------------------------|----------------------------------------------|----------|----------------------------------------------|----------------------------------------------|----------------|-------------|
| 70573848 | 2022-07-24T23:07:56.247Z | 2XNUUtqapWVeSo2XuZyrCVdPM9nc61XaVpJx7CXqpkEJ | 0        | 3pwbty7p7fhCsYzKyUzXLZxm1fXerqkboFMpMJBcUvZg | 8pMnqWqz91rD2AhKLjtnoS2Sn3mDkZGALAEFL29GFkHz | 70573845       | 3           |
| 70730864 | 2022-07-27T04:20:06.469Z | 443nF7amN2CsQDAkvW7HTiGPrnQh79xkLsQXq6PwGn4a | 215      | FU6Gbtr92CRpRcAc7HywtWZb7PSGmfPtjsDKdiS3yQkK | BTmYkcnaNYzM4rDP7pvNr5JBMtZf86LqPgqfKqs5rwd2 | 70730862       | 2           |
| 70890542 | 2022-07-29T13:06:45.497Z | 5vJMrm3ni9QiSLd4YfEoNcSJJJG65pyukQSFw6kAEpYH | 5        | FuYZsgXKcPan1J4rNrDy66pmXPCB7uJVaiuCFYWTXrr7 | 7tHP8DXMj2H4c1jvWjek1zm3DXVRiMq9g97sMbjXDutN | 70890540       | 2           |
| 71686272 | 2022-08-10T06:08:20.229Z | HCEoa28engYJNjJzhnaRbfgJVjE6o6SpR7TMFJxCD2oD | 80       | D1g4V2nSza6DnHHArffPLjUdZrKpELBePWw16G9Zw1BA | HQsPU7LmPTJZQv7MLtp8FuCmDweuY1yYM5kQVnnnjmpU | 71686270       | 2           |
| 71708382 | 2022-08-10T13:44:33.952Z | DXvNr5CTvxE3JLezcnZ49fjEcngRhcvNDfMRyMPq5pSV | 60       | Bwoe2twhMdmNcAZFUJRkvcE2PL1VrSGSrkRW1G6sMYWU | HP8GScMCYAuGmZ464EWRwvZcQqsmasJZ8VxQnvRgiqJS | 71708380       | 2           |
| 72284550 | 2022-08-18T16:04:16.826Z | ncgrtqebmFNkY7AUDBxnyVkpvzVBrrVdWogAJxhqxBS  | 272      | 3GgmMaKFkZ6prqSywPCWK6T4Z2DeZPHvRW9p4yjXyyn4 | FjAoDvodqpTeLyz44fZtoD1QwtENd6WfUK9p7wGPdvmD | 72284548       | 2           |
| 74034359 | 2022-09-12T23:20:09.631Z | 2tLjtuQZL3Uf4oj9q9VhhxtZNVJJjn1S7Rdj9GGLUeZZ | 5        | FX9hFnKJkRnb9H4DgDtcMEBhnWstppPa6S63KKrBxdNV | 2KMXPAgkKLTwiirGF6vHh55EAENAwAN7vPE6RpZefh3M | 74034357       | 2           |
| 74034901 | 2022-09-12T23:31:13.735Z | 65pN2FPDeBwSRUf387zENUfaay2NNtNCsG2c4MZBvnwv | 3        | 8xrvJdH8rSuJa86eae3TSx3T2dqvJ54XACF1FJ1PLio2 | 8D6X6DN2LbdqqCadNcD76G7Nvi37TZY7RdAMKY9HuVrJ | 74034898       | 3           |


## Next Step
For the 8 missing blocks, I will report these to the Flipside engineering team and have them re-walked to ingestion.
Please add this as a test in the `macros` directory and add it to the blocks model so it will run with the daily `dbt test` run.

**Comment by sedaghatfar** [comment]
created PR here https://github.com/sedaghatfar/near_dbt/pull/1

Did not add this as a macro as this is specific to silver blocks, (bronze does not have prev_hash without looking at the header). And will run with a generic dbt test.


Open to suggestions if this would work better as a macro

**Comment by forgxyz** [comment]
Closing - reported to engineering team and we are testing for future gaps
