### ISSUE TITLE
tx_status improvements

### ISSUE THREAD

**Issue by D0R11** [MetricsDAO/near_dbt#110]
Finding a way to improve on the `tx_status` column by including receipt information on a new column for reference since some transactions may be tagged as "success" but actually failed or vice versa

An enhancement of issue #87.

**Comment by D0R11** [comment]
An update:

From issue #87, I already tested out a new column called `receipt_status_agg_values` which is a `LIST_AGG` of all the unique receipt attributes per transaction. Originally, I tried `JSON_AGG` but it wasn't possible to do because the attributes repeat in a transaction. This idea came from checking whether a combination of unique attributes would help identify if a transaction is a success or not. What I also noticed before is that if a transaction has a Failure and Success Receipt ID in it, it still is tagged as a successful transaction in Nearblocks.

So for the past week, I picked dates at random per month for this year, queried all transactions with this specific combination, and check via Nearblocks how many of these transactions are tagged as failed or succeeded.

The query I used are as follows:

```sql
WITH receipts AS (
    SELECT
        tx_hash,
        object_keys(VALUE :outcome :status)[0] as outcome_combiner,
        VALUE :outcome :status as status_value,
        SUM(
            VALUE :outcome :gas_burnt :: NUMBER
        ) over (
            PARTITION BY tx_hash
            ORDER BY
                tx_hash DESC
        ) AS receipt_gas_burnt,
        SUM(
            VALUE :outcome :tokens_burnt :: NUMBER
        ) over (
            PARTITION BY tx_hash
            ORDER BY
                tx_hash DESC
        ) AS receipt_tokens_burnt
    FROM
        transactions,
        LATERAL FLATTEN(
            input => tx :receipt
        )
    where block_timestamp::date between '2022-01-01' and '2022-01-02' --changed the dates here
    order by tx_hash, outcome_combiner
    
), second_table as (
SELECT
    receipts.tx_hash,
    listagg(distinct outcome_combiner, ';') within group (order by outcome_combiner) as receipt_status_agg_values
FROM
    receipts
group by 1
order by receipts.tx_hash
)


select s.*, t.tx_status from second_table s
join transactions t on s.tx_hash=t.tx_hash
where receipt_status_agg_values = 'Failure;SuccessReceiptId;SuccessValue'
limit 10000
```

Disclaimer: I've only been getting 10000 each month because I think I may have caused the downtime of the Nearblocks API after calling the API multiple times in a short period of time. 

Here are the results:
| date        | Failure | Success |
|-------------|---------|---------|
| jan 1-15    | 823     | 9177    |
| feb 9-20    | 2225    | 7775    |
| march 15-25 | 9462    | 538     |
| april 6-18  | 3043    | 6957    |
| may 1-13    | 2990    | 7010    |
| june 7-21   | 1048    | 8952    |
| july 8-25   | 1087    | 8913    |
| aug 3-20    | 876     | 9124    |
| sept 1-10   | 685     | 9315    |

Observations: With the exception of March, all the other months' data are predominantly tagged as successful transactions. 24.71% of the total transactions were the only ones tagged as failure in Nearblocks while the current `tx_status` column considers all transactions as failed. I went on to query how many transactions as a whole have this specific receipt combination of Failure and Success Receipt ID:

| RECEIPT_STATUS_AGG_VALUES             |       TOTAL |
|---------------------------------------|------------:|
| Failure;SuccessValue                  |  28,176,432 |
| SuccessValue                          | 143,975,441 |
| Failure;SuccessReceiptId;SuccessValue |     529,433 |
| SuccessReceiptId;SuccessValue         |  14,928,283 |
| Failure                               |     415,893 |

There are 529,433 transactions in total and while it may just be a sample of the total population, roughly 25% of the `Failure;SuccessReceiptId;SuccessValue` combination may just be the failed transactions. 

I suggest that, as an improvement to the current `tx_status` column, I can add `receipt_status_agg_values` as a new column so that analysts will have more context on the status of the transaction.

**Comment by eevui** [comment]
Discovered some rows here that are marked failures when they are successes, according to the explorer.

```
with success_txs as (
    select tx_hash
    from {{ ref('silver__transactions') }}
    where tx_status = 'Success'
)
select
    tx_hash,
    iff(method_name = 'ft_transfer_call',
        try_parse_json(try_parse_json(args):msg),
        try_parse_json(args)
    ):actions as actions
from {{ ref('silver__actions_events_function_call') }}
where method_name in ('ft_transfer_call', 'swap')
  and tx_hash in (select tx_hash from success_txs)
  and actions is not null
  and array_size(actions) > 0
```

**Comment by D0R11** [comment]
> Discovered some rows here that are marked failures when they are successes, according to the explorer.
> 
> ```sql
> with success_txs as (
>     select tx_hash
>     from {{ ref('silver__transactions') }}
>     where tx_status = 'Success'
> )
> select
>     tx_hash,
>     iff(method_name = 'ft_transfer_call',
>         try_parse_json(try_parse_json(args):msg),
>         try_parse_json(args)
>     ):actions as actions
> from {{ ref('silver__actions_events_function_call') }}
> where method_name in ('ft_transfer_call', 'swap')
>   and tx_hash in (select tx_hash from success_txs)
>   and actions is not null
>   and array_size(actions) > 0
> ```

I'll be checking this one and the PR you linked
