### ISSUE TITLE
Bug: Table near.core.ez_dex_swaps doesnt contain enough swaps

### ISSUE THREAD

**Issue by hh2049** [MetricsDAO/near_dbt#127]
The current ez table only covers 1-way swap ( as in if one swap usdc=> near it only requires one direct exchange, and it showed on the table) 

However, this case happened because ref has a LP farm for usdc-near 

If u wanna swap say dai=> near, there  is no direct farm=> ref would choose an extra route dai=>usdt(since it has a usdt-usdc-dai farm) => near ( since it has a usdt-near farm) 

In cases like this, the swap doesn't get recorded on the EZ swap tables and has to be found on the transaction table  near.core.fact_transactions

EX: i tried to swap dai=> near which results in hash AYX1u69FVpSde68poAjasMzbKymLWGcVrEKcDKbqg9kR, this hash doesn't seem to be found on ez swap table but was recorded on the transaction table near.core.fact_transactions

**Comment by eevui** [comment]
Can confirm.

Your particular tx doesn't get brought to ez_dex_swaps since it has a different args format. Will take a look.
