### ISSUE TITLE
Several tokens missing from silver.token_labels

### ISSUE THREAD

**Issue by amasucci13** [MetricsDAO/near_dbt#135]
User reported a bug in `ez_dex_swaps`, there are no decimal values for NearX swaps. Token contract `v2-nearx.stader-labs.near` is missing from the silver.token_labels model. 

Token_labels_retriever.py returns this contract as well as several others not in silver. The python script needs to be re-ran to include these missing contracts + decimals. I tried running the script in DEV to update the seed CSV but got this error:

`OSError: Cannot save file into a non-existent directory: '../data'`

Assigning to @D0R11 since I believe they wrote the script.

**Comment by D0R11** [comment]
Will check this one, thanks for reporting!

**Comment by D0R11** [comment]
Ran the script on my end but will make a yml file as a new workflow so it'll run periodically. Will make a PR once done
