### ISSUE TITLE
Table: Action - AddKey

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#20]
Similar to FunctionCall, let's make a table for the Action Event `AddKey`.  

My proposed schema is:
- [ ] action_id
- [ ] tx_hash
- [ ] block_timestamp
- [ ] nonce
- [ ] public_key
- [ ] permission
- [ ] allowance
- [ ] method_name
- [ ] receiver_id

There are two structures here. When a user selects `FullAccess`, there are no necessary arguments.

```
{
  "access_key": {
    "nonce": 0,
    "permission": "FullAccess"
  },
  "public_key": "ed25519:5Ejo1izVBqUsHJPpGmBSSQ5ZPYoCejw2cEw2Cn7AMV1"
}
```

However, if a user selects specific methods that may be called by the contract, then the permissions object has the following structure:

```{
  "FunctionCall": {
    "allowance": "250000000000000000000000",
    "method_names": [
      "add_request",
      "add_request_and_confirm",
      "delete_request",
      "confirm"
    ],
    "receiver_id": "forrest68.near"
  }
}
```

I think we should keep all `AddKey` actions together, but should we parse the more complex `permissions` or leave as JSON? If parsed, those columns would be NULL for when `permissions` = `FullAccess`

cc: @chuxinh

**Comment by forgxyz** [comment]
Branch created with model for the `AddKey` action

**Comment by chuxinh** [comment]
If the `permisson` object has very similar structure, I think it's better just to parse them with a note in documentation that it'd be `NULL` for full access

**Comment by forgxyz** [comment]
Yes, it looks like the same structure whenever `permission` is not `FullAccess`. Ok, I will move forward with this approach. Thanks

**Comment by forgxyz** [comment]
Model available for review, linking PR momentarily.

```
root@6b6d8a5cf473:/near# dbt run -m actions_events_addkey
Running with dbt=0.21.1
Found 7 models, 61 tests, 0 snapshots, 0 analyses, 175 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

23:49:16 | Concurrency: 4 threads (target='dev')
23:49:16 |
23:49:16 | 1 of 1 START incremental model DEV.actions_events_addkey............. [RUN]
23:49:22 | 1 of 1 OK created incremental model DEV.actions_events_addkey........ [SUCCESS 1 in 5.46s]
23:49:22 |
23:49:22 | Finished running 1 incremental model in 11.98s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```
