### ISSUE TITLE
Translating Aurora-related transactions

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#32]
While NEAR transaction data can be decoded using standard base64, Aurora follows Ethereum convention. Per the Aurora devs:

> Arguments to the "submit" function on Aurora are Ethereum transactions. In the Ethereum ecosystem they are encoded using RLP and we follow that same convention in order to be compatible with Ethereum tooling.
For more info on RLP see https://eth.wiki/fundamentals/rlp
The NEAR ecosystem generally uses JSON, which is why they are easily decoded. But JSON is less efficient of an encoding than a binary format like RLP.

There are a number of Aurora related transactions with encoded data (see discussion on issue #16). We're not sure what data these messages hold, so let's decode. If useful, we should build Aurora tables out from the transaction data.

**Comment by forgxyz** [comment]
I'll give this a shot

**Comment by eevui** [comment]
I can try to take a shot at this.

**Comment by eevui** [comment]
Actually, hmm. Looking at the explorer it doesn't look like these are encoded in a way that humans are to understand.

I should have checked before implementing an rlp decoder :facepalm:

**Comment by forgxyz** [comment]
Thanks for taking a look @eevui  - I am closing this as we would need to set up Aurora as a new chain if we wanted that transactional data.
