### ISSUE TITLE
Table: Actions

### ISSUE THREAD

**Issue by jfmyers** [MetricsDAO/near_dbt#5]
As a user I want to be able to query the actions in a transaction.

Example action found in a tx:

```json
"actions": [
                            {
                                "FunctionCall": {
                                    "args": "+QHMgjmjgIMGGoCUfIdmSx4CwGkGsbMchdL7ybCKYSqAuQFk+4afLwAAAAAAAAAAAAAAAKOh71rmVhVyAjNjhi4jivqExy71AAAAAAAAAAAAAAAAyQ2w2HE0FNeFI0Ntw0dBkWRUSj8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXUqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAsSv8paVYBqr2TplSGRikvw/ECAIAAAAAAAAAAAAAAAB/qmT69UdQouPuYhFmY1/q9AarIgAAAAAAAAAAAAAAAMQsMKxswV+sm9k4YYvKoaH66FAdAAAAAAAAAAAAAAAA41IDSfR3pfbrBhBwZgSFCEmKKRuEnIqCyKBdoSgtBkzbCOVoh59sGXlRix0eenXfd+MTfnab9mK5xKAUWuzEUHkpkKd/cOZwycT352JjQJfNleyfOblF2gVuoA==",
                                    "deposit": "0",
                                    "gas": 300000000000000,
                                    "method_name": "submit"
                                }
                            }
                        ],
```

Notes:
- Args looks like base64 data
- We could decode the args using Snowflake base64 decode function and then convert the decoded value to a variant type and include it as a column in the end table
- This is downstream of stg_txs

**Columns:**
- [ ] tx_hash
- [ ] args
- [ ] encoded_args
- [ ] deposit
- [ ] gas
- [ ] method_name

**Comment by forgxyz** [comment]
Adding @mbodeantor as assignee to review.

**Comment by forgxyz** [comment]
Upon investigation, there are 7 distinct actions that might be called:

- FunctionCall
- Transfer
- AddKey
- DeployContract
- CreateAccount
- DeleteKey
- DeleteAccount

Each action has a separate structure with arguments unique from each other action. We may need to revise the plan to include all actions in one table.  
  
Perhaps the actions table includes data such as: tx_id, number of actions, list of those actions. Then, we create a table for each type of action, as the structure for each will have to be different.

Thoughts on this revision @chuxinh ?


For example, here is the actions object of a transaction with 4 distinct actions:

```json
[
  "CreateAccount",
  {
    "Transfer": {
      "deposit": "75000000000000000000000000"
    }
  },
  {
    "DeployContract": {
      "code": "wnGY4a+YYkfbkBqYqyhdQjjtHRl9Auyh7yxCGtXL8JI="
    }
  },
  {
    "FunctionCall": {
      "args": "eyJzZWNyZXRIYXNoIjoidXJQQmtnM1l6UGp0d1htRDFRTmsyeEg0Q0RLbmkrREVKN1hrcUpaSnJQZz0iLCJleHBpcmF0aW9uIjoiMTYzODcwNDIxNDAwMDAwMDAwMCIsImJ1eWVyIjoiZGNjMDBiZWZkZjViMWFhMzUwYzI0MjlkYTVkOGRiZWUzZGNmNjNiNjBjYTkzMDZjYzg4NzU3OTM1NTMwNzk3NCJ9",
      "deposit": "0",
      "gas": 10000000000000,
      "method_name": "init"
    }
  }
]
```

**Comment by chuxinh** [comment]
> *

thanks for looking into this @forgxyz. I think it'd be quite messy if we try to put everything into one table, or leave those properties per action as a json or array. 

I think can just have a raw table for actions as you said, together with dependent tables for each actions and they can be joined using `tx_id` as the primary key

**Comment by forgxyz** [comment]
Agree, I like that approach. Factor out by action type.
  
As transfer is a type of action, we should coordinate on that one @mattromano.

**Comment by drakedanner** [comment]
https://nomicon.io/RuntimeSpec/Actions

Might be an 8th type called Stake

**Comment by drakedanner** [comment]
Might be worth combining Transfer and FunctionCall types

**Comment by forgxyz** [comment]
So, after yesterday's call I like the approach of creating an actions_events table in the style of Flipside's terra.msg_events table.  
  
Proposed schema via example:  

| TX_ID                                        | BLOCK_TIMESTAMP | ACTION_INDEX | ACTION_NAME   | ACTION_DATA                                                                                                                                                                        |
|----------------------------------------------|-----------------|--------------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 7            | AddKey        | {        "access_key": {          "nonce": 0,          "permission":   "FullAccess"        },        "public_key":   "ed25519:FucLdkGvEPVrSnkvCq7wp67bgDqthyPPhf7njx1DNAME"      } |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 1            | Transfer      | {        "deposit":   "10000000000000000000000"      }                                                                                                                             |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 5            | AddKey        | {        "access_key": {          "nonce": 0,          "permission":   "FullAccess"        },        "public_key":   "ed25519:6ri55jsx2WnaSiVSSgvsdGTNWTabytgAyMh848P5pnaS"      } |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 0            | CreateAccount |                                                                                                                                                                                    |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780        | 6            | AddKey        | {        "access_key": {          "nonce": 0,          "permission":   "FullAccess"        },        "public_key":   "ed25519:82AwqRfcncRW42nDv7236P62R5yM3p7f4Wrd8Qsaux1n"      } |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 2            | AddKey        | {        "access_key": {          "nonce": 0,          "permission":   "FullAccess"        },        "public_key":   "ed25519:9G4tRGuVKT2WEczrJ8oTincD5QVMgjMVpZU3rziC1yvW"      } |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 4            | AddKey        | {        "access_key": {          "nonce": 0,          "permission":   "FullAccess"        },        "public_key":   "ed25519:2vEUmsw3vy6nqHyvsyGczZwSnuiKPku7hyrSig2aMnLr"      } |
| 7HPRPyCjtfzYLWqh1QzvgMGvWtJBtfk6uJ8BUwuhekNL | 2022-01-27 19:17:02.780         | 3            | AddKey        | {        "access_key": {          "nonce": 0,          "permission":   "FullAccess"        },        "public_key":   "ed25519:zJMMYig8eCCncFp3LJ5Fkt9CuqSN68o8RPnCBEpEqFT"      }  |
