### ISSUE TITLE
Roadmap - Open for Discussion

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#51]
Possible tables to build downstream:

- swaps
- USN
  - buys (aka swaps or mints)
  - transfers
 - NFT Activities

**Comment by forgxyz** [comment]
Staking activities, both validator and delegator side

**Comment by 0xissui** [comment]
- Metrics Daily Balances
- Metrics staking emissions(?)

**Comment by agaperste** [comment]
Hierachical analysis of account and subaccount? How many subaccount under each top level accounts, date created, gas consumed etc., might be useful to analyze top projects in the space?

**Comment by forgxyz** [comment]
Per Sync, we'll prioritize the following first:
- Swaps
- Staking actions
- USN

Discussion & design will occur in separate issues.

**Comment by forgxyz** [comment]
Another idea: bridge activity
