### ISSUE TITLE
Monitoring Dashboard

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#59]
Create a quick monitoring dashboard, similar to [this one](app.flipsidecrypto.com/dashboard/flow-status-G2WDoP), that monitors gaps in blocks and transactions.

**Comment by 0xissui** [comment]
link is broken?

**Comment by forgxyz** [comment]
Try this one: https://app.flipsidecrypto.com/dashboard/flow-status-G2WDoP

**Comment by 0xissui** [comment]
https://app.snowflake.com/us-east-1/dqa62717/near-blocks-status-dOfML2C8t
