### ISSUE TITLE
User Bug Report : Gas_used not matching the explorer in the near.transaction table

### ISSUE THREAD

**Issue by robel91** [MetricsDAO/near_dbt#74]
A user has reported that they have found a results set that doesn't match the data in the near.explorer. The user found out after querying a data from flipside_prod_db.mdao_near.transactions. Here I have attached the screenshot from the user along with the query they run.

![near_txn_bug](https://user-images.githubusercontent.com/92173230/181355250-3ca2f876-57de-48bd-ae56-c7cb2d807a0f.png)
![Mdao_near transaction_error](https://user-images.githubusercontent.com/92173230/181355347-ee7cb48f-b57c-4c48-aae6-4942cb6ce287.png)

**Comment by eevui** [comment]
First time looking at NEAR, but I'd like to pick this up!

**Comment by forgxyz** [comment]
Thanks @eevui ! I can review the PR later today.
