### ISSUE TITLE
Double counting in metrics__active_wallets.sql

### ISSUE THREAD

**Issue by sedaghatfar** [MetricsDAO/near_dbt#82]
https://github.com/MetricsDAO/near_dbt/blob/main/models/metrics/metrics__active_wallets.sql
Metrics in metrics__active_wallets.sql is double counting 
`COUNT(
            DISTINCT tx_signer
        ) AS daily_active_wallets,
        SUM(daily_active_wallets) over (
            ORDER BY
                DATE rows BETWEEN 6 preceding
                AND CURRENT ROW
        ) AS rolling_7day_active_wallets,
        SUM(daily_active_wallets) over (
            ORDER BY
                DATE rows BETWEEN 29 preceding
                AND CURRENT ROW
        ) AS rolling_30day_active_wallets`

A sum of the count distinct is adding in the sum of the daily instead of the distinct for L7/L30

Suggestion is breaking out cte's for weekly and monthly distinct counts, working on something similar for https://github.com/MetricsDAO/near_dbt/issues/14

**Comment by forgxyz** [comment]
Metrics deprecated - closing
