### ISSUE TITLE
Transaction Status to silver__transactions+

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#87]
We can infer the success of a transaction, if it succeeded or failed, from the receipts. This should be added as a field in the transactions model.

**Comment by sedaghatfar** [comment]
Proposed logic

`    , CASE 
        WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'SuccessValue' THEN 'Succeeded'
        WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'Failure'      THEN 'Failed' 
            END as status`

Test
```
SELECT 
    BLOCK_ID
    , CASE 
        WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'SuccessValue' THEN 'Succeeded'
        WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'Failure'      THEN 'Failed' 
            END as status
    , tx_hash
    , block_timestamp
    , tx
FROM NEAR_DEV.SILVER.TRANSACTIONS
WHERE block_id = 57464285
    AND tx_hash IN (
     '5KSPskhB1zn1JFETFm2CAozhNuFx8hpRb4Dyvr2ADgtS'  -- Succeeded ,
    ,'Cp6ECQXckBnoFxufSyEuyyEUrwk6yQc2SzjJSH9yX5M8') -- Failed)
```

[Succeeded  Example](https://nearblocks.io/txns/5KSPskhB1zn1JFETFm2CAozhNuFx8hpRb4Dyvr2ADgtS)
[Failed Example](https://nearblocks.io/txns/Cp6ECQXckBnoFxufSyEuyyEUrwk6yQc2SzjJSH9yX5M8)

This would require a full refresh from bronze__transactions+

**Comment by D0R11** [comment]
> Proposed logic
> 
> ` , CASE WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'SuccessValue' THEN 'Succeeded' WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'Failure' THEN 'Failed' END as status`
> 
> Test
> 
> ```
> SELECT 
>     BLOCK_ID
>     , CASE 
>         WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'SuccessValue' THEN 'Succeeded'
>         WHEN OBJECT_KEYS(tx:receipt[0]:outcome:status)[0]::string = 'Failure'      THEN 'Failed' 
>             END as status
>     , tx_hash
>     , block_timestamp
>     , tx
> FROM NEAR_DEV.SILVER.TRANSACTIONS
> WHERE block_id = 57464285
>     AND tx_hash IN (
>      '5KSPskhB1zn1JFETFm2CAozhNuFx8hpRb4Dyvr2ADgtS'  -- Succeeded ,
>     ,'Cp6ECQXckBnoFxufSyEuyyEUrwk6yQc2SzjJSH9yX5M8') -- Failed)
> ```
> 
> [Succeeded Example](https://nearblocks.io/txns/5KSPskhB1zn1JFETFm2CAozhNuFx8hpRb4Dyvr2ADgtS) [Failed Example](https://nearblocks.io/txns/Cp6ECQXckBnoFxufSyEuyyEUrwk6yQc2SzjJSH9yX5M8)
> 
> This would require a full refresh from silver__transactions+

Yup, I did something similar. Thank you for this. However, the problem arises once you join transactions to receipts, and there is more than one receipt per transaction. It could probably tag one receipt as success, and one as fail. 

So I added this snippet in the next CTE:

```sql
LAST_VALUE(
    success_or_fail
  ) over (
    PARTITION BY tx_hash
    ORDER BY
      success_or_fail DESC
  ) AS tx_status
```

The idea is if there is at least one receipt that failed, it is tagged as failed, since that's what's stated in the transaction.

And then just get the distinct tx_hash for this

**Comment by D0R11** [comment]
Will this be marked as closed for now and create a new issue for the enhancement in the future? Thanks

**Comment by forgxyz** [comment]
If you agree with the approach in Discord, @D0R11 , then it can be closed

**Comment by D0R11** [comment]
> If you agree with the approach in Discord, @D0R11 , then it can be closed

Yup, I agree.
