### ISSUE TITLE
Token Labels

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#89]
Token labels are added manually by updating the CSV file located in the `data` directory. Presently there are 31 tokens labeled. 
Querying the new `dex_swaps` model, there are 69 unlabeled tokens that we should add to this seed file. This is a manual data collection process.

Unlabeled tokens are attached in a CSV to this issue.

To submit: open a PR for review on the [near_dbt](https://github.com/MetricsDAO/near_dbt/) repository with the updated seed file.

[unlabeled_tokens.csv](https://github.com/MetricsDAO/near_dbt/files/9329389/unlabeled_tokens.csv)

-----
With the API endpoint commented below, this is no longer a manual process for wonderverse.

**Comment by forgxyz** [comment]
Flipside user Kaskoazul has provided this endpoint: https://api.stats.ref.finance/api/last-tvl  
So, this may not be such a manual process, after-all.

**Comment by D0R11** [comment]
> Flipside user Kaskoazul has provided this endpoint: https://api.stats.ref.finance/api/last-tvl So, this may not be such a manual process, after-all.

Was thinking of making a selenium script for this but there's already an endpoint. Good stuff.

**Comment by D0R11** [comment]
I'll take this

**Comment by forgxyz** [comment]
Sounds good, we should scrape the price info as well if we can set up a re-occurring job

**Comment by forgxyz** [comment]
A new token was added to `priceoracle.near` that is not labeled by us. This is causing `SYMBOL` and `TOKEN` to be null in the price table. We should add this one in the meantime, while the remaining labels are being worked on.


`4691937a7508860f876c9c0a2a617e7d9e945d4b.factory.bridge.near`
https://etherscan.io/address/0x4691937a7508860f876c9c0a2a617e7d9e945d4b
